import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";


export const metadata: Metadata = {
  title: "VenligWeb",
  description: "Generated by create next app",
  icons: {
    icon: {url: "/venligweb.png"}
  }

  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="da">
     
      <body
       
      >
        <div className="md:w-[98%] w-[95%] mx-auto">
          <Header></Header>
         <main>
        {children}
        </main>
        </div>
      </body>
    </html>
  );
}
